<?php
session_start();

// Verificar si hay sesión activa
$usuario = isset($_SESSION['usuario']) ? $_SESSION['usuario'] : null;
?>

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./styles/inicio.css">
    <link rel="icon" href="favicon.ico">
    <title>IVONNE RAMBET</title>
</head>
<body>
    
    <h1 style="text-align: center; font-size: 90px; color: rgb(150, 6, 6); font-family: italic;">RAMBET STORE</h1>

    <nav style="display: flex; justify-content: space-between; align-items: center; padding: 0px; background-color: #fff; border-bottom: 1px solid #ddd;">
            <nav>
            <?php if ($usuario): // Mostrar solo si hay sesión activa ?>
                <?php if (isset($usuario['nombre']) && isset($usuario['apellidos'])): ?>
                    <a>¡Hola, <?php echo $usuario['nombre'] . ' ' . $usuario['apellidos']; ?>!</a>
                <?php endif; ?>
            <?php endif; ?>
            </nav>
    </nav>

    <nav>
        <nav>
            <a href="inicio.php">INICIO</a>
            <a href="productos.php">PRODUCTOS</a>
            <a href="consejos.php">CONSEJOS</a>
            <a href="contacto.php">CONTACTO</a>
            <?php if (!$usuario): // Mostrar solo si no hay sesión activa ?>
                <a href="registro.php">REGISTRO</a>
                <a href="iniciarsession.php">LOGIN</a>
            <?php endif; ?>
            <?php if ($usuario && isset($usuario['role_id']) && $usuario['role_id'] == 1): ?>
                <a href="./modules/users/user.php">ADMINISTRACIÓN</a>
            <?php elseif ($usuario && isset($usuario['role_id']) && $usuario['role_id'] == 2): ?>
                <a href="./modules/users/user.php">MI PERFIL</a>
            <?php endif; ?>
            <?php if ($usuario): // Mostrar solo si hay sesión activa ?>
            <a href="./include/close.php">CERRAR SESSION</a>
            <?php endif; ?>
        </nav>
    </nav>
        
    <header>
        <!-- Image Map Generated by http://www.image-map.net/ -->
        <img src="img/banner2_tnd.webp" usemap="#image-map">

        <map name="image-map">
            <area target="_parent" alt="Jacket" title="Jacket" href="productos.php" coords="97,324,501,711" shape="rect">
            <area target="_parent" alt="bang" title="bang" href="productos.php" coords="604,222,1026,614" shape="rect">
            <area target="_parent" alt="shirt" title="shirt" href="consejos.php" coords="1101,279,1512,714" shape="rect">
        </map>
    </header>

</body>
</html>

